server:
  port: 8888

spring:
  application:
    name: QBC-Config-Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-org/your-config-repo
          default-label: main