spring:
  application:
    name: service-a
  cloud:
    config:
      uri: http://localhost:8888
      import-check:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081