spring:
  application:
    name: QBC-Gateway-Service
    gateway:
      routes:
        - id: service-a
          uri: lb://SERVICE-A
          predicates:
            - Path=/service-a/**
          filters:
            - StripPrefix=1
        - id: service-b
          uri: lb://SERVICE-B
          predicates:
            - Path=/service-b/**
          filters:
            - StripPrefix=1